### PR TITLE
Add support for stdin if environment variable is not set

### PR DESCRIPTION
**Pull request by AgapovOne**
Hello, thank you for your great cli. I liked to use cocoapods-keys previously and your package does the same in the most Swifty way :)

I would like to add a behaviour for easier variables retrieval on an integration phase. When a new developer comes to a project it should be easy for him to provide environment values.

The best way to do that for me is to fallback to `readLine()` from stdin on a local machine.

I see it as a flag option --env or --env-or-stdin where the fetcher object uses standard input. I've implemented as I see it now with two main points.

1. I saw you have an `input` property on Configuration object that should be set in `.pouch.yml` file, but I think that a flag on cli would be a better way to provide this value, because then we can call the cli with different flags on local machine or on CI.
2. Any known CI provides `CI=true` environment variable. We can use it to decide that we don't want to use stdin fallback on CI, as it would stop execution without providing proper feedback. We should reset input to `.env` when we see this variable. The discussible point here is should we respect `--env-or-stdin` flag provided with arguments even if we know that environment has `CI=true`

I'm ready to add documentation to README file when you'll have time to discuss this and review the code. It can change, of course, and I want to make it in best possible way.

Here's current cli execution example on a project with configuration:
CleanShot 2021-07-29 at 23 30 45

### CODE REVIEW

**Comment by AgapovOne** [comment]
There was a name conflict with value overriden in `EnvironmentOrStdinVariableFetcher.swift`. It worked fine in Xcode, but failed to build on CI. Fixed that issue, checked with build on my fork https://github.com/AgapovOne/Pouch/runs/3207489484

**Comment by AgapovOne** [comment]
Can we proceed with this MR, @sunshinejr?

**Comment by sunshinejr** [comment]
Hey @AgapovOne, thank you for this one! This is an idea I had as well but didn't have time to implement. It looks good, but I wanted to ask: what do you think about keeping the configuration with input, but allowing overrides with arguments? Or maybe even skip the arguments for now since you added the workaround for CI that should take care of the case where you want different input for CI/local? This is mainly because I wouldn't want to introduce breaking changes if not needed and I think we can figure something out here?

**Comment by AgapovOne** [comment]
I agree with you. Probably it's a better decision to control this behaviour through configuration file, not CLI arguments.

I also added test case for parsing input value and fixed bug with Input Codable model.

Tried to provide more information in README about env-or-stdin behaviour.

As a next feature it would be cool to save variables and retrieve them from keychain for next tries as cocoapods-keys does. That would let users to fill those secrets only once if they are unchanged. It could also be another input case for Configuration file.

**Comment by AgapovOne** [comment]
Can we proceed?

**Pull request closed without merging**
